In [1]:
import numpy as np
import time

In [2]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
#execution performance
size = 10_000_000

#python list
py_list = list(range(size))  #[1,2,3,4,.......]
start = time.time()  #Curr time value
sq_list = [x**2 for x in py_list]  #square no is calc in form of loop
end = time.time()
print(f"Python list time = {end - start} seconds")

#numpy arrays
np_arr = np.array(py_list)
start = time.time()
# vectorization - oprn in Python list that uses loops are done at bulk in numpy array
sq_array = np_arr ** 2
print(f"numpy array time = {end - start} seconds")
end = time.time()

Python list time = 1.5384936332702637 seconds
numpy array time = -1.661912202835083 seconds


In [4]:
#memory (size in terms of byte)
import sys # Python list size package
print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 800000560000000 bytes
numpy array size = 80000000 bytes


In [5]:
import numpy as np 

In [6]:
#create - from lists 
arr = np.array([1,2,3,4,5])
print (arr, type(arr) , arr.dtype , arr.shape)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2, type(arr2) , arr2.dtype , arr.shape)

arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [7]:
#create array from scratch
arr1 = np.zeros((2,3), dtype="int64") #np.zeros - prefill with zero val in the dimensions
print(arr1, arr1.shape)

arr2 = np.ones((5, )) #np.ones - creates 1D arr of ones in it
print(arr2, arr2.shape)


arr3 = np.full((3,4), 100) #np.full - prefill with a particular val
print(arr3, arr3.shape)

arr4 = np.eye((3)) #np.eye - identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(1,11,2) #np.arange - range(start,end,step)
print(arr5, arr5.shape)

arr6 = np.linspace(1,100,4) #np.linspace - evenly spaced arrays
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [9]:
#Properties
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(arr.shape)  #dimensions = m x n
print(arr.size)   #tot ele's = 9
print(arr.dtype)  #array data type (int64/128/32)
print(arr.ndim)   #no of dimensions

float_arr = arr.astype(np.float64) #type casting on existing arr (float64/128)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [11]:
#operations on arrays 

arr = np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2)) #reshapes any arr. (2 x 3) -> (3 x 2)
print(reshaped, reshaped.shape)

flattened = arr.flatten() #2D -> 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [12]:
#Indexing (similar to python lists)
arr = np.array([1,2,3,4,5])

print(arr[0]) #1
print(arr[3]) #4

arr1 = np.array([[1,2,3], [4,5,6]])
print(arr1[0][2])

1
4
3


In [14]:
#fancy indexing
arr = np.array([1,2,3,4,5])
idx = [0,1,3]
print(arr[idx])

#boolean indexing 
print(arr[arr>3]) #prints val > 3
print(arr[arr%2 == 0]) #prints even val
print(arr[arr%2 != 0]) #prints even val

[1 2 4]
[4 5]
[2 4]
[1 3 5]


In [15]:
#Slicing 
arr = np.array([1,2,3,4,5])
print(arr[1:4]) #[start,end,step]
print(arr[1:]) #start till end arr
print(arr[:4]) #all val from 0th index
print(arr[:]) #entire array
print(arr[::2]) #step ele by 2

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [18]:
#Copy vs View
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200
print(sub_list)
print(nums)

arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


In [23]:
#Data Types
arr = np.array([1,2,3,4,5])  #int val
print(arr, arr.dtype)
arr1 = np.array([1,2,3.14,4,5])  #float val
print(arr1, arr1.dtype)
arr1 = np.array([1,2,3.14,4,5,"prime"])  #string var
print(arr1, arr1.dtype)
arr2 = np.array([3 + 5j])
arr3 = np.array([2 + 3j])
print(arr2 + arr3)
print(arr2 - arr3)
arr4 = np.array(["prime",{1,2,3},3.14])
print (arr4,arr4.dtype)

[1 2 3 4 5] int64
[1.   2.   3.14 4.   5.  ] float64
['1' '2' '3.14' '4' '5' 'prime'] <U32
[5.+8.j]
[1.+2.j]
['prime' {1, 2, 3} 3.14] object
